logging: 
  level:
     org: 
        springframework: 
            cloud:  
                task: DEBUG
spring: 
  application: 
     name: chile-batch 
  cloud: 
    task: 
      initialize:
        enable: false
        
configuration: 
# Ruta de origen de los archivos
  rutaEntrada: C:\\Proyectos\BatchChile\Entrada\IdProceso23-11-2016
  rutaSalida: C:\\Proyectos\BatchChile\IdProceso
  procesosNegocio:
    - 
      ruta: C:\\Proyectos\BatchChile\IdProceso23-11-2016
      nombre: "CJMO"  
      idSolicitud: ["10","20"]
      parametros:
        - 
            nomParam: "idsolicitud"
            inicio: "10"
            fin: "20"
        - 
            nomParam: "cuenta"
            inicio: "0"
            fin: "10"          
    - 
      ruta: C:\\Proyectos\BatchChile\IdProceso23-11-2016
      nombre: "CJPYME"        
      idSolicitud: ["10","20"]
      parametros: 
        - 
            nomParam: "idsolicitud"
            inicio: "10"
            fin: "20"
        - 
            nomParam: "cuenta"
            inicio: "0"
            fin: "10" 

# Ruta de destino de los archivos CSV (no informar para usar la misma ruta que el JAR)

#uploadPath: \\an\\santander\\geoban\\CustomerContact\\SARs\\PPIOnline
uploadPath: C:\\usr\PPIOnline      

